# Generated by Django 2.2.4 on 2020-11-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
