# Generated by Django 2.2.4 on 2020-11-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(null=True)),
                ('meal', models.CharField(max_length=255)),
                ('protein', models.IntegerField(null=True)),
                ('carbohydrates', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('fat', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_eater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal_setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('calories_burned', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_finisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main_app.User')),
            ],
        ),
    ]
